' File: poseestimator.puml

@startuml(id=PoseEstimator)
class PoseEstimator {
   +Pose currentPose
   +Pose idealPose
   -float getLineAngle(float x1, float y1, float x2, float y2)
   -Pose createPose(PostProcessing :: ProcessedResults results)
   -void set_current_pose(Pose current)
   -void set_ideal_pose(Pose current)
   +Pose get_current_pose()
   +void updateCurrentPose(ProcessedResults results)
   +Pose get_ideal_pose()
   +void updateIdealPose(ProcessedResults results)
   +Pose calculatePoseChangeNeeded()
}
@enduml

@startuml(id=Joint)
enum Joint {
    Head
    Neck
    Shoulder
    Hip
    Knee
    Foot
}
@enduml

@startuml(id=ConnectedJoint)
object ConnectedJoint{
    Joint joint
    float x
    float y
    ConnectedJoint * upper_connected_joint
    float upper_angle
    ConnectedJoint * lower_connected_joint
    float lower_angle
}
@enduml

@startuml(id=Pose)
object Pose {
    ConnectedJoint head
    ConnectedJoint neck
    ConnectedJoint shoulder
    ConnectedJoint hip
    ConnectedJoint knee
    ConnectedJoint foot    
}
@enduml
