' File: postureestimator.puml

@startuml(id=PostureEstimator)
class PostureEstimator {
   +Pose current_pose
   +Pose ideal_pose
   +Pose pose_changes
   +float pose_change_threshold
   +bool good_posture   
   -float getLineAngle(PostProcessing::Coordinate coord1, PostProcessing::Coordinate coord2)
   -Pose createPoseFromResult(PostProcessing::ProcessedResults results)
   -void update_current_pose(ProcessedResults results)
   -Pose calculatePoseChanges()
   -bool checkGoodPosture()
   -bool calculateChangesAndCheckPosture()

   +PostureEstimator()
   +PoseStatus runEstimator(PostProcessing::ProcessedResults results)
   +void update_ideal_pose(PostureEstimating::Pose pose)
   +bool updateCurrentPoseAndCheckPosture(PostProcessing::ProcessedResults results)
}
@enduml

@startuml(id=Joint)
enum Joint {
    Head
    Neck
    Shoulder
    Hip
    Knee
    Foot
}
@enduml

@startuml(id=ConnectedJoint)
object ConnectedJoint{
    Joint joint
    PostProcessing::Coordinate coord
    float upper_angle
    float lower_angle
}
@enduml

@startuml(id=PoseStatus)
object PoseStatus{
    Pose ideal_pose
    Pose current_pose
    Pose pose_changes
    bool good_posture
}
@enduml

@startuml(id=Pose)
object Pose {
    ConnectedJoint head
    ConnectedJoint neck
    ConnectedJoint shoulder
    ConnectedJoint hip
    ConnectedJoint knee
    ConnectedJoint foot    
}
@enduml