@startuml

class PreProcessor {
   {field}-size_t input_image_width
   {field}-size_t input_image_height
   {field}-size_t model_width
   {field}-size_t model_height

   {method}-uint8_t* resize(uint8_t* input_image)
   {method}-float* normalise(uint8_t* resized_image)

   {method}+PreProcessor(size_t input_image_width, size_t input_image_height, 
                        size_t model_width, size_t model_height)
   {method}+PreProcessedImage run(uint8_t* input_image)
}

@enduml