@startuml

skinparam BoxPadding 10

box "FrameGenerator Thread" #Light
actor user
participant FrameGenerator
end box
box "Core Thread" #Light
participant PreProcessor
participant InferenceCore
end box
box "Post Processing Thread" #Light
participant PostProcessor
participant PostureEstimator
participant GUI
end box

user -> FrameGenerator: Video feed
user -> FrameGenerator: 
user -> FrameGenerator: 
FrameGenerator -> PreProcessor: Analyse video \nframe by frame
activate PreProcessor
note over PreProcessor
    1. Resize image 
        to suit model
    2. Fore/background 
        filtering    
end note
PreProcessor -> InferenceCore: Perform pose estimation \non image
activate InferenceCore

note over InferenceCore    
    Pass through model    
end note

InferenceCore -> PostProcessor : Output results \nof inference

activate PostProcessor

note over PostProcessor    
    1. Apply thresholding to discard
        unusable values  
    2. Filter output results
end note

PostProcessor -> PostureEstimator : Output co-ordinates \nof interest

activate PostureEstimator

note over PostureEstimator
    1. Use co-ordinates to
        determine if posture 
        is good/bad.
    2. Determine which changes
        need to be made to
        correct posture
end note

PostureEstimator -> GUI : Display video feed \nwith overlaying \nrendering of user \nposture
activate GUI

user <- PostureEstimator : Notification if poor posture

note over GUI
    Allow interaction 
    with system
end note
user <- GUI : GUI alert if poor posture

deactivate
deactivate
deactivate
deactivate
deactivate


@enduml