remote_theme: pmarsceill/just-the-docs
color_scheme: custom

aux_links:
  "View our GitHub!":
    - "//github.com/ESE-Peasy/PosturePerfection"

search_enabled: true

search:
  heading_level: 1
  rel_url: false
  button: true

footer_content: "Andrew Ritchie, Ashwin Maliampurakal, Conor Begley, Miklas Riechmann <br /> Distributed by an <a href=\"https://github.com/ESE-Peasy/PosturePerfection/blob/main/LICENSE\">GNU GPL-3.0 license.</a>"